// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnk_jheFXc1yK3wsd2itNawLU7e8BWwsk',
    appId: '1:202322666213:web:18001c37911a7f8af4aa0c',
    messagingSenderId: '202322666213',
    projectId: 'okdoz-878da',
    authDomain: 'okdoz-878da.firebaseapp.com',
    storageBucket: 'okdoz-878da.firebasestorage.app',
    measurementId: 'G-K76PTJJ782',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJqMwUANcFH0-J2tjT_UPPVtP5Z6Pkedw',
    appId: '1:202322666213:android:3acbb5d60c22d2a0f4aa0c',
    messagingSenderId: '202322666213',
    projectId: 'okdoz-878da',
    storageBucket: 'okdoz-878da.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDGgG8mCWvNeUchG_pnZGtOIbEMCnWDo',
    appId: '1:202322666213:ios:1789bd13f8cadf7ff4aa0c',
    messagingSenderId: '202322666213',
    projectId: 'okdoz-878da',
    storageBucket: 'okdoz-878da.firebasestorage.app',
    iosBundleId: 'com.example.okdozDeliveryApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDGgG8mCWvNeUchG_pnZGtOIbEMCnWDo',
    appId: '1:202322666213:ios:1789bd13f8cadf7ff4aa0c',
    messagingSenderId: '202322666213',
    projectId: 'okdoz-878da',
    storageBucket: 'okdoz-878da.firebasestorage.app',
    iosBundleId: 'com.example.okdozDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnk_jheFXc1yK3wsd2itNawLU7e8BWwsk',
    appId: '1:202322666213:web:8ee1a64c5a634c8bf4aa0c',
    messagingSenderId: '202322666213',
    projectId: 'okdoz-878da',
    authDomain: 'okdoz-878da.firebaseapp.com',
    storageBucket: 'okdoz-878da.firebasestorage.app',
    measurementId: 'G-4GF4HJDZYJ',
  );
}
